
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JTextField;
import kassa.Fprn;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainFrame.java
 *
 * Created on 31 лип 2010, 9:52:21
 */

/**
 *
 * @author жд
 */
public class mainFrame extends javax.swing.JFrame {

    private double count;
//    private GregorianCalendar day=new GregorianCalendar();
    private GregorianCalendar day=new GregorianCalendar();
    private Fprn fprn;

    public Fprn getFprn() {
        return fprn;
    }


    public GregorianCalendar getDay() {
        return day;
    }

    public void setDay(GregorianCalendar day) {
        this.day = day;
    }

    public double getCount() {
        return count;
    }

    public void setCount(double count) {
        this.count = count;
    }


    /** Creates new form mainFrame */
    public mainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        disc = new javax.swing.JTextField();
        in_debt = new javax.swing.JTextField();
        out_debt = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        exps = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        out = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        juv = new javax.swing.JLabel();
        sea = new javax.swing.JLabel();
        glass = new javax.swing.JLabel();
        cap = new javax.swing.JLabel();
        other = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Скидка:");

        jLabel2.setText("Отдали долг:");

        jLabel3.setText("Взяли в долг:");

        jLabel4.setText("Доплата:");

        jLabel5.setText("Расходы:");

        result.setFont(new java.awt.Font("Times New Roman", 1, 12));
        result.setText("jLabel6");

        disc.setText("0");
        disc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discActionPerformed(evt);
            }
        });
        disc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                discFocusLost(evt);
            }
        });
        disc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                discKeyTyped(evt);
            }
        });

        in_debt.setText("0");
        in_debt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_debtActionPerformed(evt);
            }
        });
        in_debt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                discFocusLost(evt);
            }
        });
        in_debt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                discKeyTyped(evt);
            }
        });

        out_debt.setText("0");
        out_debt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                out_debtActionPerformed(evt);
            }
        });
        out_debt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                discFocusLost(evt);
            }
        });
        out_debt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                discKeyTyped(evt);
            }
        });

        add.setText("0");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                discFocusLost(evt);
            }
        });
        add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                discKeyTyped(evt);
            }
        });

        exps.setText("0");
        exps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expsActionPerformed(evt);
            }
        });
        exps.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                discFocusLost(evt);
            }
        });
        exps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                discKeyTyped(evt);
            }
        });

        jLabel6.setText("Сняли за день:");

        out.setText("0");
        out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outActionPerformed(evt);
            }
        });
        out.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                discFocusLost(evt);
            }
        });
        out.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                discKeyTyped(evt);
            }
        });

        print.setText("Печать");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        jButton1.setText("Обновить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        juv.setText("jLabel7");

        sea.setText("jLabel8");

        glass.setText("jLabel7");

        cap.setText("jLabel7");

        other.setText("jLabel8");

        jDateChooser1.setDateFormatString("dd.MM.yyyy");
        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        jButton2.setText("..");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton3.setText("Курс");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(out)
                                    .addComponent(disc, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(in_debt)
                                    .addComponent(out_debt)
                                    .addComponent(add)
                                    .addComponent(exps)))
                            .addComponent(juv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(glass, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cap, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sea, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(other, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(result))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(print)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(disc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(in_debt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(out_debt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(exps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(juv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(glass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(other)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(result)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(print)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //setDay(new GregorianCalendar(2013, 6, 19));
//        title.setText(String.format("%1$td.%1$tm.%1$tY", day));
        jDateChooser1.setDate(day.getTime());
        ResultSet rs;
        disc.grabFocus();
        disc.selectAll();
        calc();
        String path = System.getProperty("java.library.path"); 
	System.out.println(path); 
        fprn=new Fprn();
        fprn.openDay();
        
    }//GEN-LAST:event_formWindowOpened
    private void recalc(){
//        GregorianCalendar day=new GregorianCalendar();
        result.setText(String.format("Итого касса: %.2f", getCount()-(new Double(disc.getText()))+(new Double(in_debt.getText()))-
            (new Double(out_debt.getText()))+(new Double(add.getText()))-(new Double(exps.getText()))-(new Double(out.getText()))));
        

    }
    private void discActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discActionPerformed
        in_debt.grabFocus();
        in_debt.selectAll();
    }//GEN-LAST:event_discActionPerformed

    private void in_debtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_debtActionPerformed
        out_debt.grabFocus();
        out_debt.selectAll();
    }//GEN-LAST:event_in_debtActionPerformed

    private void out_debtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_out_debtActionPerformed
        add.grabFocus();
        add.selectAll();
    }//GEN-LAST:event_out_debtActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        exps.grabFocus();
        exps.selectAll();
    }//GEN-LAST:event_addActionPerformed

    private void expsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expsActionPerformed
        out.grabFocus();
        out.selectAll();
    }//GEN-LAST:event_expsActionPerformed

    private void discFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_discFocusLost
        if (((JTextField)evt.getSource()).getText().equals("."))
            ((JTextField)evt.getSource()).setText("0");
        recalc();
    }//GEN-LAST:event_discFocusLost

    private void outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outActionPerformed
        print.grabFocus();

    }//GEN-LAST:event_outActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        Vector<Vector<String>> OutData = new Vector<Vector<String>>(0);
        NumberFormat formatter = new DecimalFormat ( "0.00" ) ;
        ResultSet rs=null;
        try{
            rs=DataSet.QueryExec(String.format("select d.numb, trim(c.name) from document d, client c where d.id_client = c.id_client and d.numb=(select min(numb)-1 from document where to_char(day,'DD.MM.YYYY')='%1$td.%1$tm.%1$tY' and id_type_doc=2) and to_char(d.day,'YYYY')=%1$tY", getDay()), false);
            if (rs.next()){
                Vector<String> Row=new Vector<String>(0);
		Row.add(rs.getString(1));
		Row.add(rs.getString(2));
		Row.add("");
		OutData.add(Row);
//                Row.clear();
            }
            rs=DataSet.QueryExec(String.format("select d.numb as num,trim(c.name) as name,d.sum*cn.curs*nvl(nullif(c.type,2),0)*nvl2(nullif(d.id_client,1593),1,0)*nvl2(nullif(d.id_client,4948),1,0) from document d, client c, curs_now cn where d.id_type_doc=2 and to_char(d.day,'DD.MM.YYYY')='%1$td.%1$tm.%1$tY' and d.id_client = c.id_client and d.id_val = cn.id_val order by numb", getDay()), false);
            while (rs.next()){
                Vector<String> Row=new Vector<String>(0);
		Row.add(rs.getString(1));
		Row.add(rs.getString(2));
		Row.add(rs.getDouble(3)!=0?formatter.format(rs.getDouble(3)):"-");
		OutData.add(Row);
//                Row.clear();
            }
            int size=OutData.size();
            OutputOO.OpenDoc("file://localhost/C:/report/Forms/report.ots", true,true);
            OutputOO.Insert(1, 1, OutData);
            OutputOO.InsertOne("Итого по накладным:", 14, true, 2, size+1);
            OutputOO.InsertOne(formatter.format(getCount()), 14, true, 3, size+1);
            OutputOO.InsertOne("Скидка:", 13, true, 2, size+3);
            OutputOO.InsertOne(disc.getText(), 13, true, 3, size+3);
            OutputOO.InsertOne("Отдали долг:", 13, true, 2, size+4);
            OutputOO.InsertOne(in_debt.getText(), 13, true, 3, size+4);
            OutputOO.InsertOne("Взяли в долг:", 13, true, 2, size+5);
            OutputOO.InsertOne(out_debt.getText(), 13, true, 3, size+5);
            OutputOO.InsertOne("Доплата:", 13, true, 2, size+6);
            OutputOO.InsertOne(add.getText(), 13, true, 3, size+6);
            OutputOO.InsertOne("Расход:", 13, true, 2, size+7);
            OutputOO.InsertOne(exps.getText(), 13, true, 3, size+7);
            OutputOO.InsertOne("Сняли:", 13, true, 2, size+9);
            OutputOO.InsertOne(out.getText(), 13, true, 3, size+9);
            OutputOO.InsertOne("Итого касса:", 14, true, 2, size+11);
            OutputOO.InsertOne(formatter.format(getCount()-(new Double(disc.getText()))+(new Double(in_debt.getText()))-
                (new Double(out_debt.getText()))+(new Double(add.getText()))-(new Double(exps.getText()))-(new Double(out.getText()))), 14, true, 3, size+11);
            OutputOO.print(1);
            OutputOO.CloseDoc();
            fprn.closeDay();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_printActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        calc();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void discKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discKeyTyped
        if (evt.getKeyChar()==','){
            evt.setKeyChar('.');
        }
//        if (!((evt.getKeyCode()>=evt.VK_0 && evt.getKeyCode()<=evt.VK_0) || evt.getKeyCode()==evt.VK_PERIOD)){
        if (!((evt.getKeyChar()>='0' && evt.getKeyChar()<='9') || evt.getKeyChar()=='.')){
            evt.setKeyChar(evt.CHAR_UNDEFINED);
        }
    }//GEN-LAST:event_discKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if (form==null)
            form=new PrintNakl(this, true,getFprn());
      form.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        if (!evt.getPropertyName().equals("date"))
            return;
//        GregorianCalendar tempDay=new GregorianCalendar(2014,05,02);
//        tempDay.setGregorianChange(jDateChooser1.getDate());
//        setDay(tempDay);
        setDay(new GregorianCalendar(jDateChooser1.getCalendar().get(Calendar.YEAR),jDateChooser1.getCalendar().get(Calendar.MONTH),jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH)));
        
        calc();
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (changeCurs==null) {
            changeCurs=new ChangeCurs(null, true);
        }
        changeCurs.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void calc(){
        ResultSet rs;
        try{
            rs=DataSet.QueryExec(String.format("select sum(d.sum*cn.curs*nvl(nullif(c.type,2),0)*nvl2(nullif(d.id_client,971),1,0)*nvl2(nullif(d.id_client,1593),1,0)*nvl2(nullif(d.id_client,4948),1,0)) from document d, client c, curs_now cn where d.id_type_doc=2 and to_char(d.day,'DD.MM.YYYY')='%1$td.%1$tm.%1$tY' and d.id_client = c.id_client and d.id_val = cn.id_val order by numb", getDay()), false);
            rs.next();
            setCount(rs.getDouble(1));
            recalc();
            rs=DataSet.QueryExec(String.format("select sum(d.sum* cn.curs) from document d, curs_now cn, client c where to_char(d.day,'DD.MM.YYYY')='%1$td.%1$tm.%1$tY' and d.id_type_doc=2 and d.id_skl=8  and c.id_client= d.id_client and c.type=1 and not(d.id_client in (1593, 4948, 5146, 732, 738, 971, 1409, 5902)) and d.id_val= cn.id_val ", getDay()), false);
            rs.next();
            juv.setText(String.format("По бижутерии - %.2f руб.", rs.getDouble(1)));
            rs=DataSet.QueryExec(String.format("select sum(d.sum* cn.curs) from document d, curs_now cn, client c where to_char(d.day,'DD.MM.YYYY')='%1$td.%1$tm.%1$tY' and d.id_type_doc=2 and not (d.id_skl in (2,8,3,9)) and c.id_client= d.id_client and c.type=1 and not(d.id_client in (1593, 4948, 5146, 732, 738, 971, 1409, 5902)) and d.id_val= cn.id_val ", getDay()), false);
            rs.next();
            other.setText(String.format("По остальным - %.2f руб.", rs.getDouble(1)));
            rs=DataSet.QueryExec(String.format("select sum(d.sum* cn.curs),sum(d.sum) from document d, curs_now cn, client c where to_char(d.day,'DD.MM.YYYY')='%1$td.%1$tm.%1$tY' and d.id_type_doc=2 and d.id_skl=2  and c.id_client= d.id_client and c.type=1 and not(d.id_client in (1593, 4948, 5146, 732, 738, 971, 1409, 5902)) and d.id_val= cn.id_val ", getDay()), false);
            rs.next();
            glass.setText(String.format("По очкам - %.2f руб.(%.2f у.е.)", rs.getDouble(1), rs.getDouble(2)));
            rs=DataSet.QueryExec(String.format("select sum(d.sum* cn.curs) from document d, curs_now cn, client c where to_char(d.day,'DD.MM.YYYY')='%1$td.%1$tm.%1$tY' and d.id_type_doc=2 and d.id_skl=3  and c.id_client= d.id_client and c.type=1 and not(d.id_client in (1593, 4948, 5146, 732, 738, 971, 1409, 5902)) and d.id_val= cn.id_val ", getDay()), false);
            rs.next();
            cap.setText(String.format("По головным уборам - %.2f руб.", rs.getDouble(1)));
            rs=DataSet.QueryExec(String.format("select sum(d.sum* cn.curs) from document d, curs_now cn, client c where to_char(d.day,'DD.MM.YYYY')='%1$td.%1$tm.%1$tY' and d.id_type_doc=2 and d.id_skl=9  and c.id_client= d.id_client and c.type=1 and not(d.id_client in (1593, 4948, 5146, 732, 738, 971, 1409, 5902)) and d.id_val= cn.id_val ", getDay()), false);
            rs.next();
            sea.setText(String.format("По морским аксесс. - %.2f руб.", rs.getDouble(1)));


        }
        catch(Exception e){
            e.printStackTrace();
        }

    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JLabel cap;
    private javax.swing.JTextField disc;
    private javax.swing.JTextField exps;
    private javax.swing.JLabel glass;
    private javax.swing.JTextField in_debt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel juv;
    private javax.swing.JLabel other;
    private javax.swing.JTextField out;
    private javax.swing.JTextField out_debt;
    private javax.swing.JButton print;
    private javax.swing.JLabel result;
    private javax.swing.JLabel sea;
    // End of variables declaration//GEN-END:variables
    private PrintNakl form;
    private ChangeCurs changeCurs;
}
